---
- set_fact:
    key_folder: '~/.ssh/'

- set_fact:
    key_path: '{{ key_folder }}id_rsa'

- name: Create ssh folder
  ansible.builtin.file:
    path: "{{ key_folder }}"
    state: directory

- name: Create ssh key on localhost
  community.crypto.openssh_keypair:
    path: "{{ key_path }}"
  delegate_to: localhost

- name: Lookup ssh pub key of ansible node
  set_fact:
    ssh_pub_key: "{{ lookup('file', key_path + '.pub') }}"
  delegate_to: localhost

- name: Upload local ssh key as authorized key
  ansible.posix.authorized_key:
    user: "{{ hypervisor_user }}"
    state: present
    key: "{{ ssh_pub_key }}"