---
- name: Create manifests directory on first master
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']
  tags: metallb

- name: Copy metallb helm manifest to first master
  template:
    src: templates/metallb_chart.yaml.j2
    dest: "/var/lib/rancher/k3s/server/manifests/metallb_chart.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']
  tags: metallb
