---
- name: Check Helm installs
  include_tasks: check_helm_installs.yml

- name: Deploy metallb IP pool CR
  include_tasks: metallb.yml
  when: metallb.enable

- name: Remove tmp directory used for manifests
  file:
    path: /tmp/k3s
    state: absent
