---
- name: Create manifests directory for temp configuration
  file:
    path: /tmp/k3s
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0755
  with_items: "{{ groups['master'] }}"
  run_once: true

- name: Copy metallb CRs manifest to first master
  template:
    src: "metallb.crs.j2"
    dest: "/tmp/k3s/metallb-crs.yaml"
    owner: "{{ ansible_user }}"
    mode: 0755
  with_items: "{{ groups['master'] }}"
  run_once: true

- name: Apply metallb CRs
  command: >-
    k3s kubectl apply -f /tmp/k3s/metallb-crs.yaml
    --timeout='{{ metal_lb_available_timeout }}'
  register: this
  changed_when: false
  run_once: true
  until: this.rc == 0
  retries: 5

- name: Test metallb-system resources
  command: >-
    k3s kubectl -n metallb-system get {{ item }}
  changed_when: false
  run_once: true
  with_items:
    - IPAddressPool
    - L2Advertisement
