- name: Copy MetalLB Helm manifest to master
  template:
    src: templates/metallb_chart.yaml.j2
    dest: "/tmp/metallb-chart.yaml"
    owner: root
    group: root
    mode: 0644
  tags: [metallb, helm-charts]

- name: Apply MetalLB Helm manifest
  command: "k3s kubectl apply -f /tmp/metallb-chart.yaml"
  tags: [metallb, helm-charts]

- name: Waiting for MetalLB pods to be ready...
  command: "k3s kubectl wait pods --all -n metallb-system --for condition=Ready"
  register: result
  retries: 10
  delay: 5
  until: result is not failed
  tags: [metallb, helm-charts]

- name: Create MetalLB CRs
  template:
    src: templates/metallb.crs.yaml.j2
    dest: /tmp/metallb.crs.yaml
    mode: 0644
    owner: root
    group: root
  tags: [metallb, helm-charts]

- name: Apply MetalLB CRs
  command: "k3s kubectl apply -f /tmp/metallb.crs.yaml"
  retries: 10
  delay: 5
  tags: [metallb, helm-charts]