- name: Copy Traefik Helm manifest to master
  template:
    src: templates/traefik_chart.yaml.j2
    dest: "/tmp/traefik-chart.yaml"
    owner: root
    group: root
    mode: 0644
  tags: [traefik, helm-charts]

- name: Apply Traefik Helm manifest
  command: "k3s kubectl apply -f /tmp/traefik-chart.yaml"
  tags: [traefik, helm-charts]

- name: Waiting for Traefik pods to be ready...
  command: "k3s kubectl wait pods --all -n traefik-system --for condition=Ready"
  register: result
  retries: 10
  delay: 5
  until: result is not failed
  tags: [traefik, helm-charts]