---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: centos9-1
    os: centos
    version: 9

  - name: centos9-2
    os: centos
    version: 9

  - name: centos9-3
    os: centos
    version: 9

  - name: centos9-4
    os: centos
    version: 9
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
    destroy: ../default/destroy.yml
  inventory:
    hosts:
      hypervisor:
        hosts:
          hypervisor-1:
            ansible_user: ${HYPERVISOR_ANSIBLE_USER}
            ansible_host: ${HYPERVISOR_ANSIBLE_HOST}
            ansible_connection: ${HYPERVISOR_ANSIBLE_CONNECTION}
            ansible_ssh_pass: ${HYPERVISOR_ANSIBLE_PASSWORD}
            ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
verifier:
  name: ansible
