- name: Restrict loading TTY line disciplines
  ansible.posix.sysctl:
    name: dev.tty.ldisc_autoload
    value: 0
    state: present

- name: Restrict unprivileged access to the perf_event_open() system call
  ansible.posix.sysctl:
    name: kernel.perf_event_paranoid
    value: 3

- name: Hardened BPF JIT compilation
  ansible.posix.sysctl:
    name: net.core.bpf_jit_harden
    value: 2

- name: Increase inotify max user instances
  ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: 8192

- name: Add a legal banner to /etc/issue, to warn unauthorized users [BANN-7126]
  ansible.builtin.copy:
    src: issue
    dest: /etc/issue
    owner: root
    group: root
    mode: '0644'

- name: Add legal banner to /etc/issue.net, to warn unauthorized users [BANN-7130]
  ansible.builtin.copy:
    src: issue.net
    dest: /etc/issue.net
    owner: root
    group: root
    mode: '0644'

- name: Fix /boot/grub/grub.cfg [FILE-7524]
  ansible.builtin.file:
    path: /boot/grub/grub.cfg
    owner: root
    group: root
    mode: '0600'

- name: Enable process accounting [ACCT-9622]
  ansible.builtin.command:
    cmd: '/usr/sbin/accton on'
