---
# tasks file for berglucht.common

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags: 
    - never
    - debug_info

- name: Create users
  include_tasks: ./users.yml

- name: Firewall
  import_tasks: ./firewall.yml
  tags:
    - firewall
  when: ufw_enable

- name: Install packages
  import_tasks: ./install.yml

- name: Sysctl
  import_tasks: ./hardening.yml

